name: CTest run
description: Run tests with CTest.

inputs:
  build_path:
    description: Build path
    required: true
  build_type:
    description: Build type (Debug, Release)
    default: Debug

runs:
  using: composite
  steps:
    - name: CTest run
      shell: pwsh
      run: >
          ctest --test-dir ${{ inputs.build_path }} -C ${{ inputs.build_type }}
