name: CI Runner
on: [push, pull_request]

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_id }}-${{ github.ref }}-runner
  cancel-in-progress: true

jobs:

  # First stage: Static checks (if fail, builds are not started).

  static-checks:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: Static Checks
    uses: ./.github/workflows/static_checks.yml

  # Second stage: Builds and tests.

  build-and-test:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: Build and Test
    needs: static-checks
    uses: ./.github/workflows/build_and_test.yml
